// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0l2Kx61QO2M4iog032ESLKtrV_KZhZPo',
    appId: '1:539805782789:web:1eaccb977c7289c8011d6c',
    messagingSenderId: '539805782789',
    projectId: 'bicoficial',
    authDomain: 'bicoficial.firebaseapp.com',
    storageBucket: 'bicoficial.appspot.com',
    measurementId: 'G-BJK3TM23Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADXF8xmEt17OwDytglCniDYiEOO-GVKhw',
    appId: '1:539805782789:android:144b29716b6b1be0011d6c',
    messagingSenderId: '539805782789',
    projectId: 'bicoficial',
    storageBucket: 'bicoficial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmNqVx0Qqok6gOAo7L-l9KCZF6vJz0808',
    appId: '1:539805782789:ios:b964168fd22f2648011d6c',
    messagingSenderId: '539805782789',
    projectId: 'bicoficial',
    storageBucket: 'bicoficial.appspot.com',
    iosBundleId: 'com.example.bicOfic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmNqVx0Qqok6gOAo7L-l9KCZF6vJz0808',
    appId: '1:539805782789:ios:b964168fd22f2648011d6c',
    messagingSenderId: '539805782789',
    projectId: 'bicoficial',
    storageBucket: 'bicoficial.appspot.com',
    iosBundleId: 'com.example.bicOfic',
  );
}
